name: studiomono

volumes:
  strapi-db-data:
    name: ${COMPOSE_PROJECT_NAME}-strapi-db-data

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}-net
  backup-scheduler-net:
    external: true
  cloudflared-net:
    external: true

services:
  strapi-db:
    container_name: ${COMPOSE_PROJECT_NAME}-strapi-db
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: ${STRAPI_DATABASE_NAME}
      POSTGRES_USER: ${STRAPI_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${STRAPI_DATABASE_PASSWORD}
    volumes:
      - strapi-db-data:/var/lib/postgresql/data
    networks:
      - default
      - backup-scheduler-net
    healthcheck:
      test: pg_isready -U ${STRAPI_DATABASE_USERNAME} -d ${STRAPI_DATABASE_NAME}

  strapi-app:
    container_name: ${COMPOSE_PROJECT_NAME}-strapi-app
    build: .
    restart: always
    env_file: strapi/.env
    environment:
      DATABASE_HOST: strapi-db
      DATABASE_NAME: ${STRAPI_DATABASE_NAME}
      DATABASE_USERNAME: ${STRAPI_DATABASE_USERNAME}
      DATABASE_PASSWORD: ${STRAPI_DATABASE_PASSWORD}
    depends_on:
      - strapi-db
    networks:
      - default
      - cloudflared-net
    healthcheck:
      test: wget -qO- http://127.0.0.1:1337
